[[auditing]]
= 审计

[[auditing.basics]]
== 基础
Spring Data提供了复杂的支持，可以透明地跟踪创建或更改实体的人以及更改发生的时间。要从该功能中受益，您必须为您的实体类配备可以使用注解或通过实现接口定义的审计元数据。

[[auditing.annotations]]
=== 基于注解的审计元数据
我们提供 `@CreatedBy` 和 `@LastModifiedBy` 来捕获创建或修改实体的用户，以及 `@CreatedDate` 和 `@LastModifiedDate` 来捕获更改发生的时间。

.经审计的实体
====
[source, java]
----
class Customer {

  @CreatedBy
  private User user;

  @CreatedDate
  private DateTime createdDate;

  // … further properties omitted
}
----
====

如您所见，可以有选择地应用注解，具体取决于您要捕获的信息。对于捕获时间点的注解，可以使用JodaTimes `DateTime`，遗留的Java `Date` 和 `Calendar`，JDK8 date/time类型，以及 `long`/`Long`。

[[auditing.interfaces]]
=== 基于接口的审计元数据
如果您不想使用注解来定义审计元数据，则可以让您的域类实现 `Auditable` 接口。它公开了所有审计属性的setter方法。

还有一个方便的基类 `AbstractAuditable`，您可以扩展它以避免需要手动实现接口方法。这样做会增加域类与Spring Data的耦合，这可能是您想要避免的。
通常，基于注解的定义审计元数据的方式是优选的，因为它具有较小的侵入性和更大的灵活性。

[[auditing.auditor-aware]]
=== AuditorAware

如果您使用 `@CreatedBy` 或 `@LastModifiedBy`，审计基础架构需要以某种方式了解当前主体。为此，我们提供了一个 `AuditorAware<T>` SPI接口，您必须实现该接口，以告知基础架构当前用户或与应用程序交互的系统。
泛型类型 `T` 定义了使用 `@CreatedBy` 或 `@LastModifiedBy` 注解的属性的类型。

这是使用Spring Security的 `Authentication` 对象的接口的示例实现：

.基于Spring Security的AuditorAware实现
====
[source, java]
----
class SpringSecurityAuditorAware implements AuditorAware<User> {

  public User getCurrentAuditor() {

    Authentication authentication = SecurityContextHolder.getContext().getAuthentication();

    if (authentication == null || !authentication.isAuthenticated()) {
      return null;
    }

    return ((MyUserDetails) authentication.getPrincipal()).getUser();
  }
}
----
====

该实现访问Spring Security提供的 `Authentication` 对象，并从其查找您在 `UserDetailsService` 实现中创建的自定义 `UserDetails` 实例。
我们这里假设您通过 `UserDetails` 实现公开域用户，但是根据找到的 `Authentication`，您也可以从任何地方查找它。

