[[mapping.fundamentals]]
= 对象映射基础

本节介绍Spring Data对象映射，对象创建，字段和属性访问，可变性和不变性的基础知识。注意，本节仅适用于不使用底层数据存储的对象映射的Spring Data模块（如JPA）。
另外，请务必查阅特定存储部分以了解特定存储的对象映射，例如索引，自定义列或字段名称等。

Spring Data对象映射的核心职责是创建域对象的实例，并将存储原生数据结构映射到这些对象。这意味着我们需要两个基本步骤：

1. 使用其中一个公开的构造函数创建实例。
2. 实例填充以实现所有公开的属性。

[[mapping.object-creation]]
== 对象创建

Spring Data会自动尝试检测持久化实体的构造函数，以用于实现该类型的对象。解析算法的工作原理如下：

1. 如果有一个无参构造函数，它将被使用。其他构造函数将被忽略。
2. 如果有单个接受参数的构造函数，它将被使用。
3. 如果有多个接受参数的构造函数，则Spring Data要使用的构造函数必须使用 `@PersistenceConstructor` 注解。

值解析假定构造函数参数名称与实体的属性名称匹配，即如果属性被填充，包括映射中的所有自定义（不同的数据存储列或字段名称等），将执行解析。
这还需要类文件中可用的参数名称信息或构造函数中存在的 `@ConstructorProperties` 注解。

可以使用Spring框架的 `@Value` 值注解使用特定存储的SpEL表达式来自定义值解析。有关更多详细信息，请参阅有关特定存储映射的部分。

[[mapping.object-creation.details]]
.对象创建内部
****

为了避免反射的开销，Spring Data对象创建使用默认在运行时生成的工厂类，它将直接调用域类构造函数。即对于此示例类型：

[source, java]
----
class Person {
  Person(String firstname, String lastname) { … }
}
----

我们将在运行时创建一个与此语义等效的工厂类：

[source, java]
----
class PersonObjectInstantiator implements ObjectInstantiator {

  Object newInstance(Object... args) {
    return new Person((String) args[0], (String) args[1]);
  }
}
----

这使我们的性能比反射大大提升了10％。要使域类符合此类优化的条件，它需要遵守一组约束：

- 它必须不是私有类
- 它必须不是非静态内部类
- 它必须不是CGLib代理类
- Spring Data使用的构造函数必须不是私有的

如果这些条件中的任何一个匹配，Spring Data将通过反射回退到实体实例化。
****

[[mapping.property-population]]
== 属性填充

实体实例一旦被创建，Spring Data就会填充该类的所有剩余持久属性。除非已经由实体的构造函数填充（即通过其构造函数参数列表使用），否则将首先填充标识符属性以允许循环对象引用的解析。
之后，尚未由构造函数填充的所有非瞬态属性在实体实例上设置。为此，我们使用以下算法：

1. 如果属性是不可变的但是公开了一个wither方法（见下文），我们使用wither来创建一个具有新属性值的新实体实例。
2. 如果定义了属性访问（即通过getter和setter访问），我们将调用setter方法。
3. 默认情况下，我们直接设置字段值。

[[mapping.property-population.details]]
.属性填充内部
****
与我们的<<mapping.object-creation.details,对象构造中的优化>>类似，我们还使用Spring Data运行时生成的访问器类与实体实例进行交互。

[source, java]
----
class Person {

  private final Long id;
  private String firstname;
  private @AccessType(Type.PROPERTY) String lastname;

  Person() {
    this.id = null;
  }

  Person(Long id, String firstname, String lastname) {
    // Field assignments
  }

  Person withId(Long id) {
    return new Person(id, this.firstname, this.lastame);
  }

  void setLastname(String lastname) {
    this.lastname = lastname;
  }
}
----

.生成的属性访问器
====
[source, java]
----
class PersonPropertyAccessor implements PersistentPropertyAccessor {

  private static final MethodHandle firstname;              <2>

  private Person person;                                    <1>

  public void setProperty(PersistentProperty property, Object value) {

    String name = property.getName();

    if ("firstname".equals(name)) {
      firstname.invoke(person, (String) value);             <2>
    } else if ("id".equals(name)) {
      this.person = person.withId((Long) value);            <3>
    } else if ("lastname".equals(name)) {
      this.person.setLastname((String) value);              <4>
    }
  }
}
----
<1> PropertyAccessor持有底层对象的可变实例。这是为了实现其他不可变属性的突变。
<2> 默认情况下，Spring Data使用字段访问来读取和写入属性值。根据 `private` 字段的可见性规则，`MethodHandles` 用于与字段交互。
<3> 该类公开了一个 `withId(…)` 方法，用于设置标识符，例如将实例插入数据存储并生成标识符时。调用 `withId(…)` 会创建一个新的 `Person` 对象。所有后续突变都将在新实例中发生，而前一个实例不会发生变化。
<4> 使用属性访问允许直接方法调用而不使用 `MethodHandle`。
====

这为我们提供了超过反射25％的性能提升。要使域类符合此类优化的条件，它需要遵守一组约束：

- 类型必须不位于默认包里或 `java` 包下。
- 类型及其构造函数必须是 `public`。
- 内部类的类型必须是 `static`。
- 使用的Java Runtime必须允许在原始的 `ClassLoader` 中声明类。Java 9和更新版本施加了某些限制。

默认情况下，如果检测到限制，Spring Data会尝试使用生成的属性访问器并回退到基于反射的访问器。
****

我们来看看以下实体：

.示例实体
====
[source, java]
----
class Person {

  private final @Id Long id;                                                <1>
  private final String firstname, lastname;                                 <2>
  private final LocalDate birthday;
  private final int age; <3>

  private String comment;                                                   <4>
  private @AccessType(Type.PROPERTY) String remarks;                        <5>

  static Person of(String firstname, String lastname, LocalDate birthday) { <6>

    return new Person(null, firstname, lastname, birthday,
      Period.between(birthday, LocalDate.now()).getYears());
  }

  Person(Long id, String firstname, String lastname, LocalDate birthday, int age) { <6>

    this.id = id;
    this.firstname = firstname;
    this.lastname = lastname;
    this.birthday = birthday;
    this.age = age;
  }

  Person withId(Long id) {                                                  <1>
    return new Person(id, this.firstname, this.lastname, this.birthday);
  }

  void setRemarks(String remarks) {                                         <5>
    this.remarks = remarks;
  }
}
----
====
<1> 该标识符属性是final，但在构造函数中设置为 `null`。该类公开了一个 `withId(…)` 方法，用于设置标识符，例如 将实例插入数据存储并生成标识符时。
原始 `Person` 实例在创建新实例时保持不变。相同的模式通常应用于存储管理的其他属性，但可能必须针对持久性操作进行更改。
<2> `firstname` 和 `lastname` 属性是可能通过getter公开的普通不可变属性。
<3> `age` 属性是一个不可变的，但是派生自 `birthday` 属性。使用所示的设计，当Spring Data使用唯一声明的构造函数时，数据库值将胜过默认值。
即使意图是计算应该是首选，重要的是这个构造函数也将 `age` 作为参数（可能忽略它），否则属性填充步骤将尝试设置age字段并因为它是不可变的并且不存在wither而失败。
<4> `comment` 属性是可变的，通过直接设置其字段来填充。
<5> `remarks` 属性是可变的，并通过直接设置 `comment` 字段或通过调用setter方法来填充。
<6> 该类公开了一个工厂方法和一个用于创建对象的构造函数。这里的核心思想是使用工厂方法而不是其他构造函数来避免通过 `@ PersistenceConstructor` 消除构造函数歧义。
相反，在工厂方法中处理属性的默认值。

== 一般建议

* _试着坚持不可变的对象_ -- 不可变对象直接创建，因为实现对象只是调用它的构造函数。此外，这可以避免使用允许客户端代码操纵对象状态的setter方法来填充域对象。
如果您需要这些，最好使它们受到包保护，以便只能通过有限数量的共存类型来调用它们。仅构造函数的实现比属性填充总体快30％。
* _提供一个全参构造函数_ -- 即使您不能或不想将实体建模为不可变值，提供一个以实体的所有属性（包括可变属性）为参数的构造函数仍然有价值，因为这样可以使对象映射跳过属性填充以获得最佳性能。
* _使用工厂方法而不是重载的构造函数来避免 ``@PersistenceConstructor``_ -- 使用最佳性能所需的全参构造函数，我们通常希望公开更多的应用程序用例特定的省略了自动生成标识符等内容的构造函数。
这是一种已建立的模式，而不是使用静态工厂方法来公开全参构造函数的这些变种。
* _确保遵守允许使用生成的实例化器和属性访问器类使用的约束_ --
* _对于要生成的标识符，仍然结合使用final字段与wither方法_ --
* _使用Lombok避免样板代码_ -- 由于持久性操作通常需要构造函数接受所有参数，因此它们的声明变成了对字段赋值的样板参数的繁琐重复，使用Lombok的 `@AllArgsConstructor` 可以最好地避免这种重复。

== Kotlin支持

Spring Data适合Kotlin规范，以允许对象创建和变异。

=== Kotlin对象创建

支持实例化Kotlin类，默认情况下所有类都是不可变的，并且需要显式属性声明来定义可变属性。考虑以下 `data` 类 `Person`：

====
[source,java]
----
data class Person(val id: String, val name: String)
----
====

上面的类使用显式构造函数编译为典型的类。我们可以通过添加另一个构造函数来自定义此类，并使用 `@PersistenceConstructor` 注解它以指示构造函数首选项：

====
[source,java]
----
data class Person(var id: String, val name: String) {

    @PersistenceConstructor
    constructor(id: String) : this(id, "unknown")
}
----
====

如果未提供参数，则Kotlin通过允许使用默认值，支持参数可选性。
当Spring Data检测到具有参数默认值的构造函数时，如果数据存储没有提供值（或者只是返回 `null`），则它将让这些参数缺席，因此Kotlin可以应用参数默认值。
考虑以下为 `name` 应用参数默认值的类：

====
[source,java]
----
data class Person(var id: String, val name: String = "unknown")
----
====

每次 `name` 参数不是结果的一部分或者它的值是 'null`，那么 `name` 默认为 `unknown`。

=== Kotlin数据类的属性填充

在Kotlin中，默认情况下所有类都是不可变的，并且需要显式属性声明来定义可变属性。考虑以下 `data` 类 `Person`：

====
[source,java]
----
data class Person(val id: String, val name: String)
----
====

这个类实际上是不可变的。它允许创建新实例，因为Kotlin生成一个 `copy(…)` 方法，该方法创建新对象实例，从现有对象复制所有属性值，并将作为参数提供的属性值应用于该方法。
