[[query-by-example]]
= 按示例查询

[[query-by-example.introduction]]
== 介绍

本章介绍按示例查询并解释如何使用。

按示例查询（QBE）是一种用户友好的具有简单接口的查询技术。它允许动态创建查询，并且不需要您编写包含字段名称的查询。实际上，按示例查询不要求使用特定存储的查询语言来编写查询。

[[query-by-example.usage]]
== 用法

按示例查询API由三部分组成：

* Probe：具有填充字段的域对象的实际示例。
* `ExampleMatcher`：`ExampleMatcher`带有有关如何匹配特定字段的详细信息。它可以在多个 `Example` 中重用。
* `Example`：`Example` 由 `Probe` 和 `ExampleMatcher` 组成。它用于创建查询。

按示例查询适用于多个用例：


* 使用一组静态或动态约束查询数据存储
* 频繁重构域对象，而不必担心破坏现有查询
* 独立于底层数据存储API工作

按示例查询也有几个限制：

* 不支持嵌套或分组属性约束，例如 `firstname = ?0 or (firstname = ?1 and lastname = ?2)`。
* 仅支持字符串的starts/contains/ends/regex匹配以及其他属性类型的精确匹配。

在开始使用按示例查询之前，您需要有一个域对象。首先，为存储库创建一个接口，如下例所示：

.示例Person对象
====
[source,java]
----
public class Person {

  @Id
  private String id;
  private String firstname;
  private String lastname;
  private Address address;

  // … getters and setters omitted
}
----
====

前面的例子显示了一个简单的域对象。您可以使用它来创建 `Example`。默认情况下，将忽略具有 `null` 值的字段，并使用特定存储的默认值匹配字符串。
可以使用工厂方法的e `of` 或使用<<query-by-example.matchers,`ExampleMatcher`>>构建`Example` 。Example是不可变的。下面列表显示了一个简单的示例：

.简单示例
====
[source,java]
----
Person person = new Person();                         <1>
person.setFirstname("Dave");                          <2>

Example<Person> example = Example.of(person);         <3>
----
<1> 创建域对象的新实例。
<2> 设置要查询的属性。
<3> 创建 `Example`。
====

理想情况下，使用存储库执行Example。为此，请让您的存储库接口扩展 `QueryByExampleExecutor<T>`。下面列表显示了来自 `QueryByExampleExecutor` 接口的摘录：

.The `QueryByExampleExecutor`
====
[source, java]
----
public interface QueryByExampleExecutor<T> {

  <S extends T> S findOne(Example<S> example);

  <S extends T> Iterable<S> findAll(Example<S> example);

  // … more functionality omitted.
}
----
====

[[query-by-example.matchers]]
== Example匹配器

Example不限于默认设置。您可以使用 `ExampleMatcher` 为字符串匹配，空值处理和特定属性的设置指定自己的默认值，如下例所示：

.具有自定义匹配的Example匹配器
====
[source,java]
----
Person person = new Person();                          <1>
person.setFirstname("Dave");                           <2>

ExampleMatcher matcher = ExampleMatcher.matching()     <3>
  .withIgnorePaths("lastname")                         <4>
  .withIncludeNullValues()                             <5>
  .withStringMatcherEnding();                          <6>

Example<Person> example = Example.of(person, matcher); <7>

----
<1> 创建域对象的新实例。
<2> 设置属性。
<3> 创建 `ExampleMatcher` 以期望所有值匹配。即使没有进一步配置，它也可以在这个阶段使用。
<4> 构造一个新的 `ExampleMatcher` 以忽略 `lastname` 属性路径。
<5> 构造一个新的 `ExampleMatcher` 以忽略 `lastname` 属性路径并包含空值。
<6> 构造一个新的 `ExampleMatcher` 以忽略 `lastname` 属性路径，包含空值，并执行后缀字符串匹配。
<7> 根据域对象和配置的 `ExampleMatcher` 创建一个新的 `Example`。
====

默认情况下，`ExampleMatcher` 期望probe上设置的所有值都匹配。如果要获得与隐式定义的任何谓词匹配的结果，请使用 `ExampleMatcher.matchingAny()`。

您可以为单个属性（例如“firstname”和“lastname”，或者嵌套属性“address.city”）指定行为。您可以使用匹配选项和区分大小写来调整它，如下例所示：

.配置匹配器选项
====
[source,java]
----
ExampleMatcher matcher = ExampleMatcher.matching()
  .withMatcher("firstname", endsWith())
  .withMatcher("lastname", startsWith().ignoreCase());
}
----
====

配置匹配器选项的另一种方法是使用Java 8 lambda。此方法创建一个要求实现者修改匹配器的回调。无需返回匹配器，因为配置选项保存在匹配器实例中。下例显示了使用lambda的匹配器：

.使用lambdas配置匹配器选项
====
[source,java]
----
ExampleMatcher matcher = ExampleMatcher.matching()
  .withMatcher("firstname", match -> match.endsWith())
  .withMatcher("firstname", match -> match.startsWith());
}
----
====

由 `Example` 创建的查询使用配置的合并视图。默认匹配设置可以在 `ExampleMatcher` 级别设置，而单个设置可以应用于特定属性路径。
除非明确定义，否则在 `ExampleMatcher` 上设置的设置将由属性路径设置继承。属性路径上的设置优先于默认设置。下表描述了各种 `ExampleMatcher` 设置的范围：

[cols="1,2", options="header"]
.`ExampleMatcher`设置的范围
|===
| 设置
| 范围

| 空值处理
| `ExampleMatcher`

| 字符串匹配
| `ExampleMatcher` 和属性路径

| 忽略属性
| 忽略属性

| 区分大小写
| `ExampleMatcher` 和属性路径

| 值转换
| 属性路径

|===
