:spring-framework-docs: http://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/
:spring-framework-javadoc: https://docs.spring.io/spring/docs/{springVersion}/javadoc-api

[[repositories]]
= 使用Spring Data存储库

Spring Data存储库抽象的目标是显著减少为各种持久性存储实现数据访问层所需的样板代码量。

[IMPORTANT]
====
_Spring Data存储库文档和您的模块_

本章介绍Spring Data存储库的核心概念和接口。本章中的信息来自Spring Data Commons模块。它使用Java Persistence API（JPA）模块的配置和代码示例。请将XML命名空间声明和要扩展的类型适配到您所使用的特定模块的等效项。
<<repositories.namespace-reference>>涵盖支持存储库API的所有Spring Data模块支持的XML配置，<<repository-query-keywords>>涵盖了存储库抽象支持的查询方法关键字。有关模块特定功能的详细信息，请参阅本文档该模块的章节。
====

[[repositories.core-concepts]]
== 核心概念
Spring Data存储库抽象中的中央接口是 `Repository`（可能不是那么令人惊讶）。它将域类以及域类的ID类型作为类型参数进行管理。此接口主要用作标记接口，用于捕获要使用的类型，并帮助您发现扩展此接口的接口。`CrudRepository` 为正在受管的实体类提供复杂的CRUD功能。

[[repositories.repository]]
.CrudRepository接口
====
[source, java]
----
public interface CrudRepository<T, ID extends Serializable>
  extends Repository<T, ID> {

  <S extends T> S save(S entity);      <1>

  Optional<T> findById(ID primaryKey); <2>

  Iterable<T> findAll();               <3>

  long count();                        <4>

  void delete(T entity);               <5>

  boolean existsById(ID primaryKey);   <6>

  // ...省略了更多功能。
}
----
<1> 保存给定的实体。
<2> 返回由给定ID标识的实体。
<3> 返回所有实体。
<4> 返回实体数量。
<5> 删除给定的实体。
<6> 指示是否存在具有给定ID的实体。
====

NOTE: 我们还提供特定持久性技术的抽象，例如 `JpaRepository` 或 `MongoRepository`。除了相当通用的持久性技术无关的接口（如CrudRepository）之外，这些接口还扩展了 `CrudRepository` 并公开了底层持久性技术的功能。

在 `CrudRepository` 之上，有一个添加了额外方法来简化对实体分页访问的 `PagingAndSortingRepository` 抽象：

.PagingAndSortingRepository
====
[source, java]
----
public interface PagingAndSortingRepository<T, ID extends Serializable>
  extends CrudRepository<T, ID> {

  Iterable<T> findAll(Sort sort);

  Page<T> findAll(Pageable pageable);
}
----
====

要按页面大小20访问 `User` 的第二页，您可以执行以下操作：

[source, java]
----
PagingAndSortingRepository<User, Long> repository = // ...访问bean
Page<User> users = repository.findAll(new PageRequest(1, 20));
----

除了查询方法之外，还可以使用count和delete查询的查询派生。

.派生Count查询
====
[source, java]
----
interface UserRepository extends CrudRepository<User, Long> {

  long countByLastname(String lastname);
}
----
====

.派生Delete查询
====
[source, java]
----
interface UserRepository extends CrudRepository<User, Long> {

  long deleteByLastname(String lastname);

  List<User> removeByLastname(String lastname);

}
----
====

[[repositories.query-methods]]
== 查询方法

标准CRUD功能存储库通常对底层数据存储进行查询。使用Spring Data，声明这些查询将分为四个步骤：

. 声明扩展Repository或其子接口之一的接口，并将其键入它应处理的域类和ID类型。
+

[source, java]
----
interface PersonRepository extends Repository<Person, Long> { … }
----

. 在接口上声明查询方法。
+

[source, java]
----
interface PersonRepository extends Repository<Person, Long> {
  List<Person> findByLastname(String lastname);
}
----

. 设置Spring为这些接口创建代理实例。通过<<repositories.create-instances.java-config,JavaConfig>>：
+

[source, java]
----
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@EnableJpaRepositories
class Config {}
----

+
或通过<<repositories.create-instances,XML配置>>：
+

[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmlns:jpa="http://www.springframework.org/schema/data/jpa"
   xsi:schemaLocation="http://www.springframework.org/schema/beans
     http://www.springframework.org/schema/beans/spring-beans.xsd
     http://www.springframework.org/schema/data/jpa
     http://www.springframework.org/schema/data/jpa/spring-jpa.xsd">

   <jpa:repositories base-package="com.acme.repositories"/>

</beans>
----

+
在此例中使用JPA命名空间。如果对任何其他存储使用存储库抽象，则需要将其更改为存储模块的相应命名空间声明，例如使用 `mongodb` 替换 `jpa`。
+
另请注意，JavaConfig变种未显式配置包，因为默认使用注解的类的包。要自定义要扫描的包，请使用特定数据存储存储库的 `@Enable…` 注解的 `basePackage…` 属性之一。

. 获取注入的存储库实例并使用。
+

[source, java]
----
class SomeClient {

  private final PersonRepository repository;

  SomeClient(PersonRepository repository) {
    this.repository = repository;
  }

  void doSomething() {
    List<Person> persons = repository.findByLastname("Matthews");
  }
}
----

以下部分详细说明了每个步骤。

[[repositories.definition]]
== 定义存储库接口

首先，定义特定域类的存储库接口。该接口必须扩展Repository，并键入域类和ID类型。如果要公开该域类型的CRUD方法，请扩展 `CrudRepository` 而不是 `Repository`。

[[repositories.definition-tuning]]
=== 微调存储库定义

通常，存储库接口扩展 `Repository`，`CrudRepository` 或 `PagingAndSortingRepository`。或者，如果您不想扩展Spring Data接口，还可以使用 `@RepositoryDefinition` 注解存储库接口。
扩展 `CrudRepository` 公开了一整套操作实体的方法。如果您希望对所公开的方法有选择性，请将要从 `CrudRepository` 公开的方法复制到域存储库中。

NOTE: 这允许您在提供的Spring Data Repositories功能之上定义自己的抽象。

.有选择地公开CRUD方法
====
[source, java]
----
@NoRepositoryBean
interface MyBaseRepository<T, ID extends Serializable> extends Repository<T, ID> {

  Optional<T> findById(ID id);

  <S extends T> S save(S entity);
}

interface UserRepository extends MyBaseRepository<User, Long> {
  User findByEmailAddress(EmailAddress emailAddress);
}
----
====

在第一步中，您为所有域存储库定义了一个公共基本接口，并公开了 `findById(…)` 以及 `save(…)`。这些方法被路由到Spring Data提供的您所选存储的基本存储库实现中（例如，如果使用JPA，那么实现是 `SimpleJpaRepository`），因为它们匹配 `CrudRepository` 中的方法签名。
因此，`UserRepository` 现在可以保存用户，并通过id查找单个用户，以及触发查询以通过其电子邮件地址查找 `Users`。

NOTE: 中间存储库接口使用 `@NoRepositoryBean` 注解。确保将该注解添加到Spring Data不应在运行时创建实例的所有存储库接口。


[[repositories.nullability]]
=== 存储库方法的Null处理

从Spring Data 2.0开始，返回单个聚合实例的存储库CRUD方法使用Java 8的 `Optional` 来指示可能缺少值。除此之外，Spring Data支持在查询方法上返回以下包装类型：

* `com.google.common.base.Optional`
* `scala.Option`
* `io.vavr.control.Option`
* `javaslang.control.Option`（随着Javaslang废弃而废弃）

或者，查询方法可以选择根本不使用包装类型。然后通过返回 `null` 来指示缺少查询结果。返回集合，集合替代，包装器和流的存储库方法保证永远不会返回 `null`，而是返回相应的空表示。
有关详细信息，请参阅<<repository-query-return-types>>。

[[repositories.nullability.annotations]]
==== 可空性注解

您可以使用link:{spring-framework-docs}/core.html#null-safety[Spring框架的可空性注解]表达存储库方法的可空性约束 。它们提供了一种工具友好的方法，并在运行时选择 `null` 检查：

* {spring-framework-javadoc}/org/springframework/lang/NonNullApi.html[`@NonNullApi`] – 在包级别上使用，声明参数和返回值的默认行为是不接受或生成 `null` 值。
* {spring-framework-javadoc}/org/springframework/lang/NonNull.html[`@NonNull`] – 用于不得为 `null` 的参数或返回值（应用 `@NonNullApi` 的包的参数或返回值不需要）。
* {spring-framework-javadoc}/org/springframework/lang/Nullable.html[`@Nullable`] – 用于可为 `null` 的参数或返回值。

Spring注解是使用 https://jcp.org/en/jsr/detail?id=305[JSR 305]注解（一种休眠但广泛传播的JSR）进行元注释的。
JSR 305元注解允许工具供应商，如 https://www.jetbrains.com/help/idea/nullable-and-notnull-annotations.html[IDEA]、http://help.eclipse.org/oxygen/index.jsp?topic=/org.eclipse.jdt.doc.user/tasks/task-using_external_null_annotations.htm[Eclipse]或link:https://kotlinlang.org/docs/reference/java-interop.html#null-safety-and-platform-types[Kotlin]以通用方式提供null安全支持，而无需硬编码支持Spring注解。
要为查询方法启用运行时可空性约束检查，需要在 `package-info.java` 中使用Spring的 `@NonNullApi` 来激活包级别的非可空性：

.在 `package-info.java` 中声明非可空性
====
[source, java]
----
@org.springframework.lang.NonNullApi
package com.acme;
----
====

一旦存在非空默认，就会在运行时验证存储库查询方法调用的可空性约束。如果查询执行结果违反了定义的约束，则抛出异常；即方法由于某些原因会返回 `null` 但声明为非可空（在存储库所在的包上使用注解默认定义的）。
如果您想再次选择可空的结果，请在方法上有选择地使用 `@Nullable`。使用上述结果包装器类型将继续按预期工作，即空结果将被转换为表示缺少的值。

.使用不同的可空性约束
====
[source, java]
----
package com.acme;                                                       <1>

import org.springframework.lang.Nullable;

interface UserRepository extends Repository<User, Long> {

  User getByEmailAddress(EmailAddress emailAddress);                    <2>

  @Nullable
  User findByEmailAddress(@Nullable EmailAddress emailAdress);          <3>

  Optional<User> findOptionalByEmailAddress(EmailAddress emailAddress); <4>
}
----
<1> 存储库在我们已定义非空行为的包（或子包）中。
<2> 当执行的查询未产生结果时，将抛出 `EmptyResultDataAccessException`。当传递给方法的 `emailAddress` 为 `null` 时，将抛出 `IllegalArgumentException`。
<3> 当执行的查询未产生结果时，将返回 `null`。还接受 `null` 作为 `emailAddress` 的值。
<4> 当执行的查询未产生结果时，将返回 `Optional.empty()`。当传递给该方法的 `emailAddress` 为 `null` 时，将抛出 `IllegalArgumentException`。
====

[[repositories.nullability.kotlin]]
==== 基于Kotlin存储库的可空性

Kotlin具有烤入该语言中的 https://kotlinlang.org/docs/reference/null-safety.html[可空性约束定义]。Kotlin代码编译为字节码，它不使用方法签名而是编译进的元数据表达可空性约束。
确保在项目中包含 `kotlin-reflect` JAR，以便启用Kotlin的可空性约束内省。Spring Data存储库使用语言机制来定义这些约束以应用相同的运行时检查：

.在Kotlin存储库上使用可空性约束
====
[source, kotlin]
----
interface UserRepository : Repository<User, String> {

  fun findByUsername(username: String): User     <1>

  fun findByFirstname(firstname: String?): User? <2>
}
----
<1> 该方法将参数和结果都定义为非可空（Kotlin默认值）。Kotlin编译器拒绝将 `null` 传递给该方法的方法调用。如果查询执行产生空结果，将抛出 `EmptyResultDataAccessException`。
<2> 此方法接受 `null` 作为 `firstname` 的参数，如果查询执行未产生结果，则返回 `null`。
====

[[repositories.multiple-modules]]
=== 使用具有多个Spring Data模块的存储库

在应用程序中使用唯一的Spring Data模块会使事情变得简单，因为定义范围内的所有存储库接口都绑定到该Spring Data模块。有时，应用程序需要使用多个Spring Data模块。
在这种情况下，存储库定义需要区分持久性技术。当Spring Data在类路径上检测到多个存储库工厂时，它进入严格的存储库配置模式。严格配置需要存储库或域类的详细信息来确定存储库定义的Spring Data模块绑定：

1. 如果存储库定义<<repositories.multiple-modules.types,扩展特定模块的存储库>>，那么它是特定Spring Data模块的有效候选者。
2. 如果域类<<repositories.multiple-modules.annotations,使用特定模块类型的注解进行注解>>，则它是特定Spring Data模块的有效候选者。
Spring Data模块接受第三方注解（例如JPA的 `@Entity`）或提供自己的注解（例如Spring Data MongoDB/Spring Data Elasticsearch的 `@Document`）。

[[repositories.multiple-modules.types]]
.使用特定模块接口的存储库定义
====
[source, java]
----
interface MyRepository extends JpaRepository<User, Long> { }

@NoRepositoryBean
interface MyBaseRepository<T, ID extends Serializable> extends JpaRepository<T, ID> {
  …
}

interface UserRepository extends MyBaseRepository<User, Long> {
  …
}
----
`MyRepository` 和 `UserRepository` 在其类型层次中扩展 `JpaRepository`。它们是Spring Data JPA模块的有效候选者。
====

.使用通用接口的存储库定义
====
[source, java]
----
interface AmbiguousRepository extends Repository<User, Long> {
 …
}

@NoRepositoryBean
interface MyBaseRepository<T, ID extends Serializable> extends CrudRepository<T, ID> {
  …
}

interface AmbiguousUserRepository extends MyBaseRepository<User, Long> {
  …
}
----
`AmbiguousRepository` 和 `AmbiguousUserRepository` 在其类型层次中仅扩展了 `Repository` 和 `CrudRepository`。虽然在使用唯一Spring Data模块时这是完全正常的，但是多个模块无法区分这些存储库应该绑定到哪个特定的Spring Data。
====

[[repositories.multiple-modules.annotations]]
.使用带注解的域类的存储库定义
====
[source, java]
----
interface PersonRepository extends Repository<Person, Long> {
 …
}

@Entity
class Person {
  …
}

interface UserRepository extends Repository<User, Long> {
 …
}

@Document
class User {
  …
}
----
`PersonRepository` 引用使用JPA注解 `@Entity` 进行注解的 `Person`，因此该存储库显然属于Spring Data JPA。`UserRepository` 引用使用Spring Data MongoDB的 `@Document` 注解进行注解的 `User`.
====

.使用具有混合注解的域类的存储库定义
====
[source, java]
----
interface JpaPersonRepository extends Repository<Person, Long> {
 …
}

interface MongoDBPersonRepository extends Repository<Person, Long> {
 …
}

@Entity
@Document
class Person {
  …
}
----
此示例显示了使用JPA和Spring Data MongoDB注解的域类。它定义了两个存储库，`JpaPersonRepository` 和 `MongoDBPersonRepository`。
意图一个用于JPA，另一个用于MongoDB用法。Spring Data不再能够将存储库分开，从而导致未定义的行为。
====

<<repositories.multiple-modules.types,存储库类型详细信息>>和<<repositories.multiple-modules.annotations,区分域类注解>>用于严格存储库配置以标识特定Spring Data模块的存储库候选。
在同一域类型上使用多个持久性技术特定的注解是可能的，并允许跨多种持久性技术重用域类型，但是，Spring Data不再能够确定绑定存储库的唯一模块。

区分存储库的最后一种方法是对存储库基础包划定范围。基础包定义了扫描存储库接口定义的起点，这意味着将存储库定义放在相应的包中。默认情况下，注解驱动的配置使用配置类的包。<<repositories.create-instances.spring,基于XML配置中的基础包>>是必需的。

.基础包的注解驱动配置
====
[source, java]
----
@EnableJpaRepositories(basePackages = "com.acme.repositories.jpa")
@EnableMongoRepositories(basePackages = "com.acme.repositories.mongo")
interface Configuration { }
----
====

[[repositories.query-methods.details]]
== 定义查询方法

存储库代理有两种方法可以从方法名称派生特定存储的查询。它可以直接从方法名称派生查询，也可以使用手动定义的查询。可用选项取决于实际存储。
但是，必须有一个策略来决定创建什么实际查询。我们来看看可用的选项。

[[repositories.query-methods.query-lookup-strategies]]
=== 查询查找策略

存储库基础结构可以使用以下策略来解析查询。您可以在XML配置通过 `query-lookup-strategy` 属性在命名空间配置策略，或者在Java配置通过Enable${store}Repositories注解的 `queryLookupStrategy` 属性配置策略。
特定数据存储可能不支持某些策略。

- `CREATE` 尝试从查询方法名称构造特定存储的查询。一般方法是从方法名称中删除一组已知的前缀，并解析方法的其余部分。您可以在<<repositories.query-methods.query-creation>>中阅读有关查询构造的更多信息。

- `USE_DECLARED_QUERY` 尝试查找声明的查询，如果找不到，则抛出异常。查询可以通过某处的注解来定义，也可以通过其他方式声明。查阅特定存储的文档以查找该存储的可用选项。
如果存储库基础结构在引导时未找到该方法的声明查询，则它将失败。

- `CREATE_IF_NOT_FOUND`（默认）组合 `CREATE` 和 `USE_DECLARED_QUERY`。它首先查找声明的查询，如果没找到，它会创建一个基于方法名称的自定义查询。
这是默认的查找策略，因此，如果您未明确配置任何内容，则使用此策略。它允许通过方法名称快速查询定义，还可以根据需要引入声明的查询来对这些查询进行自定义调整。

[[repositories.query-methods.query-creation]]
=== 查询创建

构建到Spring Data存储库基础结构中的查询构建器机制对于构建存储库实体的约束查询很有用。该机制从方法剥离前缀 `find…By`、`read…By`、`query…By`、`count…By` 和 `get…By` 并开始解析其余部分。
引入子句可以包含其他表达式，例如在要创建的查询上设置不同标志的 `Distinct`。但是，第一个 `By` 充当分隔符以指示实际条件的开始。
在最基本的层面上，您可以在实体属性上定义条件，并使用 `And` 和 `Or` 将它们连接起来。

.从方法名称创建查询
====
[source, java]
----
interface PersonRepository extends Repository<User, Long> {

  List<Person> findByEmailAddressAndLastname(EmailAddress emailAddress, String lastname);

  // 为查询启用distinct标志
  List<Person> findDistinctPeopleByLastnameOrFirstname(String lastname, String firstname);
  List<Person> findPeopleDistinctByLastnameOrFirstname(String lastname, String firstname);

  // 启用忽略单个属性的大小写
  List<Person> findByLastnameIgnoreCase(String lastname);
  // 为所有合适的属性启用忽略大小写
  List<Person> findByLastnameAndFirstnameAllIgnoreCase(String lastname, String firstname);

  // 为查询启用静态ORDER BY
  List<Person> findByLastnameOrderByFirstnameAsc(String lastname);
  List<Person> findByLastnameOrderByFirstnameDesc(String lastname);
}
----
====

解析方法的实际结果取决于您为其创建查询的持久性存储。但是，有一些一般要注意的事项。

- 表达式通常是与可级联的运算符结合的属性遍历。您可以将属性表达式与 `AND` 和 `OR` 组合在一起。您还可以获得对属性表达式的运算符支持，例如 `Between`、`LessThan`、`GreaterThan` 和 `Like`。
支持的运算符可能因数据存储而异，因此请参阅参考文档的相应部分。

- 方法解析器支持为单个属性（例如，`findByLastnameIgnoreCase(…)`）或为支持忽略大小写类型的所有属性（通常为 `String` 实例，例如 `findByLastnameAndFirstnameAllIgnoreCase(…)`）设置 `IgnoreCase` 标志。
是否支持忽略大小写可能因存储而异，因此请参阅参考文档中有关特定存储的查询方法的相关章节。

- 您可以通过将 `OrderBy` 子句附加到引用属性的查询方法并提供排序方向（`Asc` 或 `Desc`）来应用静态排序。要创建支持动态排序的查询方法，请参阅<<repositories.special-parameters>>。

[[repositories.query-methods.query-property-expressions]]
=== 属性表达式

属性表达式只能引用托管实体的直接属性，如前面的示例所示。在创建查询时，您已确保解析的属性是托管域类的属性。但是，您也可以通过遍历嵌套属性来定义约束。假设 `Person` 有（具有 `ZipCode` 的）`Address`。这种情况下，方法名

[source, java]
----
List<Person> findByAddressZipCode(ZipCode zipCode);
----

创建属性遍历 `x.address.zipCode`。解析算法首先将整个部分（`AddressZipCode`）解释为属性，并检查域类中是否具有该名称的属性（未大写）。如果算法成功，则使用该属性。
否则，算法会在驼峰命名部分将源从右侧分成头部和尾部并尝试查找相应的属性 - 在我们的示例中，为 `AddressZip` 和 `Code`。
如果算法找到具有该头部的属性，则获取尾部，并继续从那里向下构建树，按照刚才描述的方式将尾部分割。如果第一次分割不匹配，算法会将分割点向左移动（`Address`、`ZipCode`）并继续。

虽然这应该适用于大多数情况，但算法可能会选择错误的属性。假设 `Person` 类有 `addressZip` 属性。算法将在第一次拆分轮中匹配，选择错误的属性，然后失败（因为 `addressZip` 的类型可能没有 `code` 属性）。

要解决这种歧义，可以在方法名称中使用 `_` 来手动定义遍历点。所以我们的方法名称如下：

[source, java]
----
List<Person> findByAddress_ZipCode(ZipCode zipCode);
----

因为我们将下划线字符视为保留字符，所以我们强烈建议遵循标准Java命名约定（即，*不*在属性名称中使用下划线，而是使用驼峰命名法）。

[[repositories.special-parameters]]
=== 特殊参数处理
要处理查询中的参数，请定义方法参数，如前面示例中所示。除此之外，基础结构还可以识别某些特定类型，如 `Pageable` 和 `Sort`，以动态地对查询应用分页和排序。

.在查询方法中使用Pageable、Slice和Sort
====
[source, java]
----
Page<User> findByLastname(String lastname, Pageable pageable);

Slice<User> findByLastname(String lastname, Pageable pageable);

List<User> findByLastname(String lastname, Sort sort);

List<User> findByLastname(String lastname, Pageable pageable);
----
====

第一个方法允许您将 `org.springframework.data.domain.Pageable` 实例传递给查询方法，以便为您的静态定义查询动态添加分页。`Page` 知道可用元素和页面的总数。
它通过基础设施触发count查询计算总数来实现。由于这可能代价昂贵（取决于所使用的存储），可以改为返回 `Slice`。`Slice` 只知道下一个 `Slice` 是否可用，这在遍历更大的结果集时可能就足够了。

排序选项也通过 `Pageable` 实例处理。如果只需要排序，请在方法中添加 `org.springframework.data.domain.Sort` 参数。如您所见，也可以返回 `List`。
在这种情况下，不会创建构建实际 `Page` 实例所需的其他元数据（反过来，这意味着不会发出必要的附加count查询）；相反，它限制查询仅查找给定范围的实体。

NOTE: 要了解整个查询的页数，您必须触发额外的计数查询。默认情况下，此查询是从您实际触发的查询派生的。

[[repositories.limit-query-result]]
=== 限制查询结果

查询方法的结果可以通过 `first` 或 `top` 关键字来限制，这些关键字可以互换使用。可选的数值可以附加到top或first，以指定要返回的最大结果大小。
如果省略该数字，则假定结果大小为1。

.使用 `Top` 和 `First` 限制查询结果大小
====
[source, java]
----
User findFirstByOrderByLastnameAsc();

User findTopByOrderByAgeDesc();

Page<User> queryFirst10ByLastname(String lastname, Pageable pageable);

Slice<User> findTop3ByLastname(String lastname, Pageable pageable);

List<User> findFirst10ByLastname(String lastname, Sort sort);

List<User> findTop10ByLastname(String lastname, Pageable pageable);
----
====

限制表达式还支持 `Distinct`  关键字。此外，对于将结果集限制为一个实例的查询，支持将结果包装到 `Optional` 关键字中。

如果将分页或切片应用于限制查询分页（以及可用页数的计算），则将其应用于有限结果中。

NOTE: 请注意，通过 `Sort` 参数将结果与动态排序相结合，可以表示 'K' 最小元素和 'K' 最大元素的查询方法。

[[repositories.query-streaming]]
=== 流化查询结果

可以通过使用Java 8 `Stream<T>` 作为返回类型来递增地处理查询方法的结果。不是简单地将查询结果包装在 `Stream` 中，而是使用特定数据存储的方法来执行流化。

.使用Java 8 `Stream<T>` 流化查询结果
====
[source, java]
----
@Query("select u from User u")
Stream<User> findAllByCustomQueryAndStream();

Stream<User> readAllByFirstnameNotNull();

@Query("select u from User u")
Stream<User> streamAllPaged(Pageable pageable);
----
====
NOTE: `Stream` 可能包含底层数据存储特定的资源，因此必须在使用后关闭。您可以使用 `close()` 方法或使用Java 7 try-with-resources块手动关闭 `Stream`。

.在try-with-resources块中使用 `Stream<T>` 结果
====
[source, java]
----
try (Stream<User> stream = repository.findAllByCustomQueryAndStream()) {
  stream.forEach(…);
}
----
====
NOTE: 并非所有Spring Data模块当前都支持 `Stream<T>` 作为返回类型。

[[repositories.query-async]]
=== 异步查询结果

可以使用link:{spring-framework-docs}/integration.html#scheduling[Spring的异步方法执行异步能力]异步执行存储库查询。这意味着该方法在调用时立即返回，而实际查询执行发生在已提交给Spring TaskExecutor的任务中。

====
[source, java]
----
@Async
Future<User> findByFirstname(String firstname);               <1>

@Async
CompletableFuture<User> findOneByFirstname(String firstname); <2>

@Async
ListenableFuture<User> findOneByLastname(String lastname);    <3>
----
<1> 使用 `java.util.concurrent.Future` 作为返回类型。
<2> 使用Java 8 `java.util.concurrent.CompletableFuture` 作为返回类型。
<3> 使用 `org.springframework.util.concurrent.ListenableFuture` 作为返回类型。
====

[[repositories.create-instances]]
== 创建存储库实例
在本节中，您将为定义的存储库接口创建实例和bean定义。一种方法是使用随每个支持存储库机制的Spring Data模块一起提供的Spring命名空间，尽管我们通常建议使用Java-Config样式配置。

[[repositories.create-instances.spring]]
=== XML配置
每个Spring Data模块都包含一个repositories元素，允许您简单地定义Spring为您扫描的基础包。

.通过XML启用Spring Data存储库
====
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans:beans xmlns:beans="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://www.springframework.org/schema/data/jpa"
  xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/data/jpa
    http://www.springframework.org/schema/data/jpa/spring-jpa.xsd">

  <repositories base-package="com.acme.repositories" />

</beans:beans>
----
====

在前面的示例中，指示Spring在 `com.acme.repositories` 及其所有子包中扫描扩展 `Repository` 或其子接口之一的接口。
对于找到的每个接口，基础结构都会注册特定持久性技术的 `FactoryBean`，以创建处理查询方法调用的相应代理。
每个bean都是在从接口名称派生的bean名称下注册的，因此 `UserRepository` 的接口将在 `userRepository` 下注册。`base-package` 属性允许使用通配符，以便您可以定义扫描包的模式。

==== 使用过滤器
默认情况下，基础结构会选择扩展位于已配置的基本包下的特定持久性技术的 `Repository` 子接口的每个接口，并为其创建一个bean实例。但是，您可能希望对哪些接口为其创建bean实例进行更细粒度的控制。
为此，请在 `<repositories />` 元素中使用 `<include-filter />` 和 `<exclude-filter />` 元素。语义完全等同于Spring的上下文命名空间中的元素。有关详细信息，请参阅link:{spring-framework-docs}/core.html#beans-scanning-filters[Spring参考文档]的这些元素。

例如，要将某些接口从实例化为存储库中排除，可以使用以下配置：

.使用exclude-filter元素
====
[source, xml]
----
<repositories base-package="com.acme.repositories">
  <context:exclude-filter type="regex" expression=".*SomeRepository" />
</repositories>
----
====

此示例排除了以 `SomeRepository` 结尾的所有接口的实例化。

[[repositories.create-instances.java-config]]
=== JavaConfig
还可以通过在JavaConfig类上使用特定存储的 `@Enable${store}Repositories` 注解来触发存储库基础结构。有关Spring容器的基于Java配置的介绍，请参阅参考文档。footnote:[link:{spring-framework-docs}/core.html#beans-java[Spring参考文档中的JavaConfig]]

启用Spring Data存储库的示例配置类似于以下内容：

.基于注解的存储库配置示例
====
[source, java]
----
@Configuration
@EnableJpaRepositories("com.acme.repositories")
class ApplicationConfiguration {

  @Bean
  EntityManagerFactory entityManagerFactory() {
    // …
  }
}
----
====

NOTE: 上面的示例使用JPA特定的注解，您可以根据实际使用的存储模块进行更改。这同样适用于 `EntityManagerFactory` bean的定义。请参阅有关特定存储配置的部分。

[[repositories.create-instances.standalone]]
=== 独立使用
您还可以在Spring容器之外使用存储库基础结构 - 例如，在CDI环境中。您仍然在类路径中需要一些Spring库，但通常也可以通过编程方式设置存储库。
提供存储库支持的Spring Data模块提供了特定持久性技术的RepositoryFactory，您可以按如下方式使用它：

.存储库工厂的独立使用
====
[source, java]
----
RepositoryFactorySupport factory = … // Instantiate factory here
UserRepository repository = factory.getRepository(UserRepository.class);
----
====

[[repositories.custom-implementations]]
== Spring Data存储库的自定义实现
本节介绍存储库自定义以及片段如何构成复合存储库。

当查询方法需要不同的行为或无法通过查询派生实现时，则需要提供自定义实现。Spring Data存储库轻松允许您提供自定义存储库代码，并将其与通用CRUD抽象和查询方法功能集成。

[[repositories.single-repository-behavior]]
=== 自定义单个存储库
要使用自定义功能丰富存储库，首先定义片段接口和自定义功能的实现。然后让您的存储库接口另外从片段接口扩展。

.自定义存储库功能的接口
====
[source, java]
----
interface CustomizedUserRepository {
  void someCustomMethod(User user);
}
----
====

.自定义存储库功能的实现
====
[source, java]
----
class CustomizedUserRepositoryImpl implements CustomizedUserRepository {

  public void someCustomMethod(User user) {
    // Your custom implementation
  }
}
----
====

NOTE: 与片段接口相比，要查找的类最重要的部分是名称的 `Impl` 后缀。

实现本身不依赖于Spring Data，可以是常规的Spring bean。因此，您可以使用标准依赖注入行为来注入对其他bean的引用（例如 `JdbcTemplate`），参与切面等等。

.对存储库接口的更改
====
[source, java]
----
interface UserRepository extends CrudRepository<User, Long>, CustomizedUserRepository {

  // Declare query methods here
}
----
====

让存储库接口扩展片段接口。这样做可以组合CRUD和自定义功能，并使其可供客户端使用。

Spring Data存储库通过使用组成存储库组合的片段来实现。片段是基本存储库，功能切面（例如<<core.extensions.querydsl,QueryDsl>>），以及自定义接口及其实现。
每次向存储库接口添加接口时，都可以通过添加片段来增强组合。每个Spring Data模块都提供了基本存储库和存储库切面的实现。

.片段及其实现
====
[source, java]
----
interface HumanRepository {
  void someHumanMethod(User user);
}

class HumanRepositoryImpl implements HumanRepository {

  public void someHumanMethod(User user) {
    // Your custom implementation
  }
}

interface EmployeeRepository {

  void someEmployeeMethod(User user);

  User anotherEmployeeMethod(User user);
}

class ContactRepositoryImpl implements ContactRepository {

  public void someContactMethod(User user) {
    // Your custom implementation
  }

  public User anotherContactMethod(User user) {
    // Your custom implementation
  }
}
----
====

.对存储库接口的更改
====
[source, java]
----
interface UserRepository extends CrudRepository<User, Long>, HumanRepository, ContactRepository {

  // Declare query methods here
}
----
====

存储库可以由多个按其声明顺序导入的自定义实现组成。自定义实现的优先级高于基本实现和存储库切面。如果两个片段提供相同的方法签名，则此排序允许您覆盖基本存储库和切面方法并解决歧义。
存储库片段不限于在单个存储库接口中使用。多个存储库可以使用一个片段接口，允许在不同的存储库中重用自定义。

.片段覆盖 `save(…)`
====
[source, java]
----
interface CustomizedSave<T> {
  <S extends T> S save(S entity);
}

class CustomizedSaveImpl<T> implements CustomizedSave<T> {

  public <S extends T> S save(S entity) {
    // Your custom implementation
  }
}
----
====

.自定义存储库接口
====
[source, java]
----
interface UserRepository extends CrudRepository<User, Long>, CustomizedSave<User> {
}

interface PersonRepository extends CrudRepository<Person, Long>, CustomizedSave<Person> {
}
----
====

==== 配置
如果使用命名空间配置，则存储库基础结构会尝试通过扫描我们找到存储库所在包下面的类来自动检测自定义实现片段。这些类需要遵循将命名空间元素的 `repository-impl-postfix` 属性附加到找到的片段接口名称的命名约定。此后缀默认为 `Impl`。

.Configuration example
====
[source, xml]
----
<repositories base-package="com.acme.repository" />

<repositories base-package="com.acme.repository" repository-impl-postfix="FooBar" />
----
====

第一个配置示例尝试查找 `com.acme.repository.CustomizedUserRepositoryImpl` 类，以充当自定义存储库实现，第二个示例尝试查找 `com.acme.repository.CustomizedUserRepositoryFooBar`。

[[repositories.single-repository-behaviour.ambiguity]]
===== 解决歧义

如果在不同的包中找到具有匹配类名的多个实现，则Spring Data使用bean名来标识要使用的正确bean。

上面介绍的 `CustomizedUserRepository` 的以下两个自定义实现，将选择第一个实现。它的bean名称是 `customizedUserRepositoryImpl`，与片段接口（`CustomizedUserRepository`）加上后缀 `Impl` 相匹配。

.解决歧义实现
====
[source, java]
----
package com.acme.impl.one;

class CustomizedUserRepositoryImpl implements CustomizedUserRepository {

  // Your custom implementation
}
----
[source, java]
----
package com.acme.impl.two;

@Component("specialCustomImpl")
class CustomizedUserRepositoryImpl implements CustomizedUserRepository {

  // Your custom implementation
}
----
====

如果使用 `@Component("specialCustom")` 注解 `UserRepository` 接口，则bean名称加 `Impl` 然后匹配定义在 `com.acme.impl.two` 中的存储库实现，它被选择而不是第一个。

===== 手动装配

如果您的自定义实现仅使用基于注解的配置和自动装配，则刚才显示的方法效果很好，因为它被视为任何其他Spring bean。如果您的实现片段bean需要特殊装配，您可以简单地声明bean并根据刚才描述的约定对其进行命名。
然后，基础结构按名称引用手动定义的bean定义，而不是自己创建一个。

.手动装配自定义实现
====
[source, xml]
----
<repositories base-package="com.acme.repository" />

<beans:bean id="userRepositoryImpl" class="…">
  <!-- further configuration -->
</beans:bean>
----
====

[[repositories.customize-base-repository]]
=== 自定义基本存储库

当您想要定制基本存储库行为以便所有存储库受到影响时，前面的方法需要自定义所有存储库接口。相反，要更改所有存储库的行为，您需要创建一个扩展特定持久性技术的存储库基类的实现。然后，此类充当存储库代理的自定义基类。

.自定义存储库基类
====
[source, java]
----
class MyRepositoryImpl<T, ID extends Serializable>
  extends SimpleJpaRepository<T, ID> {

  private final EntityManager entityManager;

  MyRepositoryImpl(JpaEntityInformation entityInformation,
                          EntityManager entityManager) {
    super(entityInformation, entityManager);

    // Keep the EntityManager around to used from the newly introduced methods.
    this.entityManager = entityManager;
  }

  @Transactional
  public <S extends T> S save(S entity) {
    // implementation goes here
  }
}
----
====

WARNING: 该类需要具有特定存储的存储库工厂实现所使用的超类的构造函数。如果存储库基类具有多个构造函数，则覆盖使用 `EntityInformation` 加上特定于存储的基础结构对象（例如 `EntityManager` 或模板类）的构造函数。

最后一步是使Spring Data基础结构知道自定义存储库基类。在JavaConfig中，可以使用 `@Enable…Repositories` 注解的 `repositoryBaseClass` 属性来执行此操作：

.使用JavaConfig配置自定义存储库基类
====
[source, java]
----
@Configuration
@EnableJpaRepositories(repositoryBaseClass = MyRepositoryImpl.class)
class ApplicationConfiguration { … }
----
====

XML命名空间中提供了相应的属性。

.使用XML配置自定义存储库基类
====
[source, xml]
----
<repositories base-package="com.acme.repository"
     base-class="….MyRepositoryImpl" />
----
====

[[core.domain-events]]
== 从聚合根发布事件

由存储库管理的实体是聚合根。在域驱动设计应用程序中，这些聚合根通常会发布域事件。Spring Data提供了 `@DomainEvents` 注解，可以在聚合根的方法上使用，使发布尽可能简单。

.从聚合根公开域事件
====
[source, java]
----
class AnAggregateRoot {

    @DomainEvents <1>
    Collection<Object> domainEvents() {
        // ...返回您想在此处发布的事件
    }

    @AfterDomainEventPublication <2>
    void callbackMethod() {
       // ...可能清理域事件列表
    }
}
----
<1> 使用 `@DomainEvents` 的方法可以返回单个事件实例或事件集合。它不能接收任何参数。
<2> 所有事件发布后，有一个使用 `@AfterDomainEventPublication` 注解的方法。它可用于潜在地清除已发布的事件列表。
====

每次调用Spring Data存储库的其中一个 `save(…)` 方法时，都会调用这些方法。


[[core.extensions]]
== Spring Data扩展

本节介绍了一组使Spring Data可以在各种上下文中使用的Spring Data扩展。目前，大多数集成都针对Spring MVC。

[[core.extensions.querydsl]]
=== Querydsl扩展

http://www.querydsl.com/[Querydsl]是一个框架，可以通过其流畅的API构建静态类型的类SQL查询。

几个Spring Data模块通过 `QuerydslPredicateExecutor` 提供与Querydsl的集成。

.QuerydslPredicateExecutor接口
====
[source, java]
----
public interface QuerydslPredicateExecutor<T> {

  Optional<T> findById(Predicate predicate);  <1>

  Iterable<T> findAll(Predicate predicate);   <2>

  long count(Predicate predicate);            <3>

  boolean exists(Predicate predicate);        <4>

  // … more functionality omitted.
}
----
<1> 查找并返回与 `Predicate` 匹配的单个实体。
<2> 查找并返回与 `Predicate` 匹配的所有实体。
<3> 返回与 `Predicate` 匹配的实体数。
<4> 返回是否存在与 `Predicate` 匹配的实体。
====

要使用Querydsl支持，请在存储库接口上简单地扩展 `QuerydslPredicateExecutor`。

.存储库上的Querydsl集成
====
[source, java]
----
interface UserRepository extends CrudRepository<User, Long>, QuerydslPredicateExecutor<User> {

}
----
====

上面的示例允许使用Querydsl `Predicate` 实例编写类型安全查询。

[source, java]
----
Predicate predicate = user.firstname.equalsIgnoreCase("dave")
	.and(user.lastname.startsWithIgnoreCase("mathews"));

userRepository.findAll(predicate);
----

[[core.web]]
=== Web支持

NOTE: 本节包含Spring Data的Web支持文档，因为它是从1.6范围内的Spring Data Commons实现的。由于新引入的支持更改了许多内容，因此我们在<<web.legacy>>中保留了以前行为的文档。

如果模块支持存储库编程模型，则Spring Data模块附带各种Web支持。Web相关的东西需要类路径上的Spring MVC JAR，其中一些甚至提供与Spring HATEOASfootnote:[Spring HATEOAS - link:$$https://github.com/SpringSource/spring-hateoas$$[https://github.com/SpringSource/spring-hateoas]]的集成。通常，通过在JavaConfig配置类中使用 `@EnableSpringDataWebSupport` 注解来启用集成支持。

.启用Spring Data web支持
====
[source, java]
----
@Configuration
@EnableWebMvc
@EnableSpringDataWebSupport
class WebConfiguration {}
----
====

`@EnableSpringDataWebSupport` 注解注册了一些我们稍后会讨论的组件。还将检测类路径上的Spring HATEOAS，并为它注册集成组件（如果存在）。

或者，如果使用XML配置，请将 `SpringDataWebSupport` 或 `HateoasAwareSpringDataWebSupport` 注册为Spring bean：

.在XML中启用Spring Data web支持
====
[source, xml]
----
<bean class="org.springframework.data.web.config.SpringDataWebConfiguration" />

<!-- 如果使用Spring HATEOAS，请注册这个*而不是*前者 -->
<bean class="org.springframework.data.web.config.HateoasAwareSpringDataWebConfiguration" />
----
====

[[core.web.basic]]
==== 基本Web支持
上面显示的配置设置将注册一些基本组件：

- `DomainClassConverter` 让Spring MVC从请求参数或路径变量解析存储库管理的域类实例。
- `HandlerMethodArgumentResolver` 实现让Spring MVC从请求参数解析 `Pageable` 和 `Sort` 实例。

[[core.web.basic.domain-class-converter]]
===== DomainClassConverter
`DomainClassConverter` 允许您在Spring MVC控制器方法签名中直接使用域类型，因此您无需通过存储库手动查找实例：

.在方法签名中使用域类型的Spring MVC控制器
====
[source, java]
----
@Controller
@RequestMapping("/users")
class UserController {

  @RequestMapping("/{id}")
  String showUserForm(@PathVariable("id") User user, Model model) {

    model.addAttribute("user", user);
    return "userForm";
  }
}
----
====

如您所见，该方法直接接收User实例，无需进一步查找。可以通过让Spring MVC首先将路径变量转换为该域类的id类型来解析实例，并最终通过在注册为该域类型的存储库实例上调用 `findById(…)` 来访问该实例。

NOTE: 目前，存储库必须实现 `CrudRepository` 才有资格被发现进行转换。

[[core.web.basic.paging-and-sorting]]
===== 用于Pageable和Sort的HandlerMethodArgumentResolvers
上面的配置片段还注册了 `PageableHandlerMethodArgumentResolver` 以及 `SortHandlerMethodArgumentResolver`的实例。该注册启用 `Pageable` 和 `Sort` 作为有效的控制器方法参数：

.使用Pageable作为控制器方法参数
====
[source, java]
----
@Controller
@RequestMapping("/users")
class UserController {

  private final UserRepository repository;
  
  UserController(UserRepository repository) {
    this.repository = repository;
  }

  @RequestMapping
  String showUsers(Model model, Pageable pageable) {

    model.addAttribute("users", repository.findAll(pageable));
    return "users";
  }
}
----
====

此方法签名导致Spring MVC尝试使用以下默认配置从请求参数派生Pageable实例：

.Pageable实例的请求参数评估
[options = "autowidth"]
|===============
|`page`|要检索的页面。0索引并默认为0。
|`size`|要检索的页面大小，默认为20。
|`sort`|应以 `property,property(,ASC\|DESC)` 格式排序的属性。默认排序方向是升序。如果要切换方向，请使用多个 `sort` 参数 - 例如，`?sort=firstname&sort=lastname,asc`。
|===============

要自定义此行为，请分别注册实现 `PageableHandlerMethodArgumentResolverCustomizer` 或 `SortHandlerMethodArgumentResolverCustomizer` 接口的bean。调用其 `customize()` 方法，让您更改设置。如下例所示。

[source, java]
----
@Bean SortHandlerMethodArgumentResolverCustomizer sortCustomizer() {
    return s -> s.setPropertyDelimiter("<-->");
}
----

如果设置现有 `MethodArgumentResolver` 属性不足以满足您的需要，请扩展 `SpringDataWebConfiguration` 或启用HATEOAS的等效项，覆盖 `pageableResolver()` 或 `sortResolver()` 方法，并导入您的自定义配置文件，而不是使用 `@Enable`注解。

如果需要从请求中解析多个 `Pageable` 或 `Sort` 实例（例如，对于多个表），可以使用Spring的 `@Qualifier` 注解以区分彼此。请求参数必须以 `${qualifier}_` 为前缀。所以对于像这样的方法签名：

[source, java]
----
String showUsers(Model model,
      @Qualifier("foo") Pageable first,
      @Qualifier("bar") Pageable second) { … }
----

你必须填充 `foo_page` 和 `bar_page` 等。

传递给方法的默认 `Pageable` 等同于 `new PageRequest(0, 20)`，但可以在 `Pageable` 参数上使用 `@PageableDefault` 注解进行自定义。

[[core.web.pageables]]
==== 对Pageables的超媒体支持
Spring HATEOAS附带了一个表示模型类（`PagedResources`），它允许使用必要的 `Page` 元数据以及让客户端轻松浏览页面的链接丰富 `Page` 实例的内容。
将Page转换为 `PagedResources` 是通过Spring HATEOAS `ResourceAssembler` 接口的实现（`PagedResourcesAssembler`）完成的。

.使用PagedResourcesAssembler作为控制器方法参数
====
[source, java]
----
@Controller
class PersonController {

  @Autowired PersonRepository repository;

  @RequestMapping(value = "/persons", method = RequestMethod.GET)
  HttpEntity<PagedResources<Person>> persons(Pageable pageable,
    PagedResourcesAssembler assembler) {

    Page<Person> persons = repository.findAll(pageable);
    return new ResponseEntity<>(assembler.toResources(persons), HttpStatus.OK);
  }
}
----
====

启用上面所示的配置，允许将 `PagedResourcesAssembler` 用作控制器方法参数。在其上调用 `toResources(…)` 具有以下效果：

- `Page` 的内容将成为 `PagedResources` 实例的内容。
- `PagedResources` 对象附加了 `PageMetadata` 实例，并使用 `Page` 和底层 `PageRequest`中的信息填充。
- `PagedResources` 可能会附加 `prev` 和 `next` 链接，具体取决于页面的状态。链接将指向调用的方法映射到的URI。添加到方法的分页参数与 `PageableHandlerMethodArgumentResolver` 的设置相匹配，以确保稍后可以解析链接。

假设我们在数据库中有30个Person实例。您现在可以触发请求（`GET http://localhost:8080/persons`）并看到类似于以下内容的输出：

[source, javascript]
----
{ "links" : [ { "rel" : "next",
                "href" : "http://localhost:8080/persons?page=1&size=20 }
  ],
  "content" : [
     … // 20 Person instances rendered here
  ],
  "pageMetadata" : {
    "size" : 20,
    "totalElements" : 30,
    "totalPages" : 2,
    "number" : 0
  }
}
----

您会看到assembler生成了正确的URI，并且还选择了默认配置以将即将请求的参数解析为 `Pageable`。这意味着，如果更改该配置，链接将自动遵循更改。
默认情况下，assembler指向调用它的控制器方法，但是可以通过交换自定义 `Link` 来定制，以用作构建分页链接的基础，这会重载 `PagedResourcesAssembler.toResource(…)` 方法。

[[core.web.binding]]
==== Web数据绑定支持

Spring Data投影（一般在<<projections>>中描述）可用于通过使用 http://goessner.net/articles/JsonPath/[JSONPath]表达式（需要 https://github.com/json-path/JsonPath[Jayway JasonPath]）或 https://www.w3.org/TR/xpath-31/[XPath]表达式（需要 https://xmlbeam.org/[XmlBeam]）来绑定传入的请求有效负载。

.使用JSONPath或XPath表达式绑定HTTP有效负载
====
[source, java]
----
@ProjectedPayload
public interface UserPayload {

  @XBRead("//firstname")
  @JsonPath("$..firstname")
  String getFirstname();

  @XBRead("/lastname")
  @JsonPath({ "$.lastname", "$.user.lastname" })
  String getLastname();
}
----
====

上面的类型可以用作Spring MVC处理器方法参数，也可以在 `RestTemplate` 的方法之一上使用 `ParameterizedTypeReference`。上面方法声明将尝试在给定文档中的任何位置查找 `firstname`。
`lastname` XML查找在传入文档的顶层执行。其中的JSON变种首先尝试顶级 `lastname`，但如果前者未返回值，则还尝试嵌套在 `user` 子文档中的 `lastname`。
如果源文档的结构可以很容易地减轻，而不必接触调用公开方法的客户端（通常是基于类的有效负载绑定的缺点），那么这种方式就会改变。

支持嵌套投影，如<<projections>>中所述。如果方法返回复杂的非接口类型，则使用 `ObjectMapper` 来映射最终值。

对于Spring MVC，只要 `@EnableSpringDataWebSupport` 激活并且类路径上所需的依赖可用，就会自动注册必要的转换器。
要与 `RestTemplate` 一起使用，请手动注册 `ProjectingJackson2HttpMessageConverter`（JSON）或 `XmlBeamHttpMessageConverter`。

有关更多信息，请参阅规范 https://github.com/spring-projects/spring-data-examples[Spring Data示例存储库]中的 https://github.com/spring-projects/spring-data-examples/tree/master/web/projection[web投影示例]。

[[core.web.type-safe]]
==== Querydsl Web支持

对于那些具有 http://www.querydsl.com/[QueryDSL]集成的存储，可以从 `Request` 查询字符串中包含的属性派生查询。

这意味着给定来自先前示例的 `User` 对象的查询字符串

[source,text]
----
?firstname=Dave&lastname=Matthews
----

可以使用 `QuerydslPredicateArgumentResolver`解析为

[source,text]
----
QUser.user.firstname.eq("Dave").and(QUser.user.lastname.eq("Matthews"))
----

NOTE: 当在类路径中找到Querydsl时，该功能将与 `@EnableSpringDataWebSupport` 一起自动启用。

向方法签名添加 `@QuerydslPredicate` 可提供随时可用的可以通过 `QuerydslPredicateExecutor` 运行的 `Predicate`。

TIP: 通常从方法的返回类型中解析类型信息。由于那些信息不一定与域类型匹配，因此使用 `QuerydslPredicate` 的 `root` 属性可能是个好主意。

====
[source,java]
----
@Controller
class UserController {

  @Autowired UserRepository repository;

  @RequestMapping(value = "/", method = RequestMethod.GET)
  String index(Model model, @QuerydslPredicate(root = User.class) Predicate predicate,    <1>
          Pageable pageable, @RequestParam MultiValueMap<String, String> parameters) {

    model.addAttribute("users", repository.findAll(predicate, pageable));

    return "index";
  }
}
----
<1> 将查询字符串参数解析为匹配 `User`的 `Predicate`。
====

默认绑定如下：

* 简单属性上的 `Object` 为 `eq`。
* 类似集合属性上的 `Object` 为 `contains`。
* 简单属性上的 `Collection` 为 `in`。

这些绑定可以通过 `@QuerydslPredicate` 的 `bindings` 属性或使用Java 8 `默认方法` 并添加 `QuerydslBinderCustomizer` 方法到存储库接口来自定义。

====
[source,java]
----
interface UserRepository extends CrudRepository<User, String>,
                                 QuerydslPredicateExecutor<User>,                <1>
                                 QuerydslBinderCustomizer<QUser> {               <2>

  @Override
  default void customize(QuerydslBindings bindings, QUser user) {

    bindings.bind(user.username).first((path, value) -> path.contains(value))    <3>
    bindings.bind(String.class)
      .first((StringPath path, String value) -> path.containsIgnoreCase(value)); <4>
    bindings.excluding(user.password);                                           <5>
  }
}
----
<1> `QuerydslPredicateExecutor` 提供对 `Predicate` 的特定finder方法的访问。
<2> 定义在存储库接口上的 `QuerydslBinderCustomizer` 将被自动选择并简化为 `@QuerydslPredicate(bindings=...)`。
<3> 将 `username` 属性的绑定定义为简单的contains绑定。
<4> 将 `String` 属性的默认绑定定义为不区分大小写的contains匹配。
<5> 从 `Predicate` 解析中排除 _password_ 属性。
====

[[core.repository-populators]]
=== 存储库填充器
如果您使用Spring JDBC模块，您可能熟悉使用SQL脚本填充 `DataSource` 的支持。虽然它不使用SQL作为数据定义语言，但它在存储库级别上提供了类似的抽象，因为它必须与存储无关。
因此，填充器支持XML（通过Spring的OXM抽象）和JSON（通过Jackson）来定义用于填充存储库的数据。

假设您有一个具有以下内容的 `data.json` 文件：

.JSON定义的数据
====
[source, javascript]
----
[ { "_class" : "com.acme.Person",
 "firstname" : "Dave",
  "lastname" : "Matthews" },
  { "_class" : "com.acme.Person",
 "firstname" : "Carter",
  "lastname" : "Beauford" } ]
----
====

您可以使用Spring Data Commons中提供的存储库命名空间的populator元素来填充存储库。要将前面的数据填充到PersonRepository，请执行下列操作：

.声明Jackson存储库填充器
====
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:repository="http://www.springframework.org/schema/data/repository"
  xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/data/repository
    http://www.springframework.org/schema/data/repository/spring-repository.xsd">

  <repository:jackson2-populator locations="classpath:data.json" />

</beans>
----
====

此声明导致 `data.json` 文件通过Jackson `ObjectMapper` 读取和反序列化。

将通过检查JSON文档的 `_class` 属性来确定将JSON对象解组到的类型。基础结构最终将选择适当的存储库来处理反序列化的对象。

相反，使用XML来定义应该填充存储库的数据，可以使用 `unmarshaller-populator` 元素。您将其配置为使用Spring OXM提供的XML marshaller选项之一。
请参阅link:{spring-framework-docs}/data-access.html#oxm[Spring参考文档]获取更多细节。

.声明解组存储库填充器（使用JAXB）
====
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:repository="http://www.springframework.org/schema/data/repository"
  xmlns:oxm="http://www.springframework.org/schema/oxm"
  xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/data/repository
    http://www.springframework.org/schema/data/repository/spring-repository.xsd
    http://www.springframework.org/schema/oxm
    http://www.springframework.org/schema/oxm/spring-oxm.xsd">

  <repository:unmarshaller-populator locations="classpath:data.json"
    unmarshaller-ref="unmarshaller" />

  <oxm:jaxb2-marshaller contextPath="com.acme" />

</beans>
----
====

[[web.legacy]]
=== 遗留Web支持

[[web-domain-class-binding]]
==== Spring MVC的域类Web绑定

鉴于您正在开发Spring MVC Web应用程序，您通常必须从URL解析域类ID。默认情况下，您的任务是将请求参数或URL部分转换为域类，然后将其传递给下面的层，或者直接在实体上执行业务逻辑。这看起来像这样：

[source, java]
----
@Controller
@RequestMapping("/users")
class UserController {

  private final UserRepository userRepository;

  UserController(UserRepository userRepository) {
    Assert.notNull(repository, "Repository must not be null!");
    this.userRepository = userRepository;
  }

  @RequestMapping("/{id}")
  String showUserForm(@PathVariable("id") Long id, Model model) {

    // 执行id的空检查
    User user = userRepository.findById(id);
    // 执行user的空检查

    model.addAttribute("user", user);
    return "user";
  }
}
----

首先，为每个控制器声明存储库依赖，以分别查找由控制器或存储库管理的实体。查找实体也是样板文件，因为它总是 `findById(…)` 调用。幸运的是，Spring提供了注册自定义组件的方法，这些组件允许将 `String` 值转换为任意类型。

[[web.legacy.property-editors]]
===== PropertyEditors

对于3.0之前的Spring版本，必须使用简单的Java `PropertyEditors`。为了与它集成，Spring Data提供了 `DomainClassPropertyEditorRegistrar`，它查找在 `ApplicationContext` 中注册的所有Spring Data存储库，并为托管域类注册自定义的 `PropertyEditor`。

[source, xml]
----
<bean class="….web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter">
  <property name="webBindingInitializer">
    <bean class="….web.bind.support.ConfigurableWebBindingInitializer">
      <property name="propertyEditorRegistrars">
        <bean class="org.springframework.data.repository.support.DomainClassPropertyEditorRegistrar" />
      </property>
    </bean>
  </property>
</bean>
----

如果您已按照前面的示例配置了Spring MVC，则可以按如下方式配置控制器，这样可以减少大量的混乱和样板。

[source, java]
----
@Controller
@RequestMapping("/users")
class UserController {

  @RequestMapping("/{id}")
  String showUserForm(@PathVariable("id") User user, Model model) {

    model.addAttribute("user", user);
    return "userForm";
  }
}
----

