[[customizing-sdr.configuring-the-rest-url-path]]
= 配置REST URL路径

您可以配置导出的JPA存储库资源的URL路径段。为此，请在类级别或查询方法级别添加注解。

默认情况下，导出器使用域类的名称公开 `CrudRepository`。Spring Data REST还应用 https://github.com/atteo/evo-inflector[Evo Inflector]来复数化这个单词。考虑以下存储库定义：

====
[source,java]
----
interface PersonRepository extends CrudRepository<Person, Long> {}
----
====

前面示例定义的存储库在 `http://localhost:8080/persons/` 公开。

要更改存储库的导出方式，请在类级别添加 `@RestResource` 注解，如下例所示：

====
[source,java]
----
@RepositoryRestResource(path = "people")
interface PersonRepository extends CrudRepository<Person, Long> {}
----
====

前面示例定义的存储库可以在 `http://localhost:8080/people/` 访问。

如果您定义了查询方法，那么这些方法也默认通过其名称公开，如下例所示：

====
[source,java]
----
interface PersonRepository extends CrudRepository<Person, Long> {

  List<Person> findByName(String name);
}
----
====

前面示例中的方法在 `http://localhost:8080/persons/search/findByName` 公开。

NOTE: 所有查询方法资源都在 `search` 资源下公开。

要更改公开此查询方法的URL段，可以再次使用 `@RestResource` 注解，如下例所示：

====
[source,java]
----
@RepositoryRestResource(path = "people")
interface PersonRepository extends CrudRepository<Person, Long> {

  @RestResource(path = "names")
  List<Person> findByName(String name);
}
----
====

现在，前面示例中的查询方法在 `http://localhost:8080/people/search/names` 公开。

== 处理 `rel` 属性

由于这些资源都是可发现的，因此您还可以影响 `rel` 属性在导出器发送的链接中的显示方式。

例如，在默认配置中，如果您向 `http://localhost:8080/persons/search` 发出请求以找出所公开的查询方法，您获得一个类似于以下的链接列表：

====
[source,javascript]
----
{
  "_links" : {
    "findByName" : {
      "href" : "http://localhost:8080/persons/search/findByName"
    }
  }
}
----
====

要更改 `rel` 值，请在 `@RestResource` 注解上使用 `rel` 属性，如下例所示：

====
[source,java]
----
@RepositoryRestResource(path = "people")
interface PersonRepository extends CrudRepository<Person, Long> {

  @RestResource(path = "names", rel = "names")
  List<Person> findByName(String name);
}
----
====

前面示例产生以下链接值：

====
[source,javascript]
----
{
  "_links" : {
    "names" : {
      "href" : "http://localhost:8080/persons/search/names"
    }
  }
}
----
====

NOTE: 这些JSON片段假设您使用的是Spring Data REST的 http://stateless.co/hal_specification.html[HAL]默认格式。可以关闭HAL，这会导致输出看起来不同。但是覆盖 `rel` 名称的能力完全独立于呈现格式。

您可以更改存储库的 `rel`，如下例所示：

====
[source,java]
----
@RepositoryRestResource(path = "people", rel = "people")
interface PersonRepository extends CrudRepository<Person, Long> {

  @RestResource(path = "names", rel = "names")
  List<Person> findByName(String name);
}
----
====

更改存储库的 `rel` 会更改顶级名称，如下例所示：

====
[source,javascript]
----
{
  "_links" : {
    "people" : {
      "href" : "http://localhost:8080/people"
    },
    …
  }
}
----
====

在前面输出中显示的顶级片段中：

* `path = "people"` 将 `href` 中的值从 `/persons` 更改为 `/people`。
* `rel = "people"` 将链接的名称从 `persons` 更改为 `people`。

当您导航到此存储库的 `search` 资源时，finder方法的 `@RestResource` 注解已如下更改路径：

====
[source,javascript]
----
{
  "_links" : {
    "names" : {
      "href" : "http://localhost:8080/people/search/names"
    }
  }
}
----
====

存储库定义中的此注解集合已导致以下更改：

* 存储库级别注解的 `path = "people"` 通过 `/people` 反映在基URI中。
* 包含finder方法为您提供 `/people/search`。
* `path = "names"` 创建了URI `/people/search/names`。
* `rel = "names"` 将链接的名称从 `findByNames` 更改为 `names`。

[[customizing-sdr.hiding-repositories]]
== 隐藏某些存储库、查询方法或字段

您可能根本不想导出某个存储库，存储库上的查询方法或实体的字段。示例包括隐藏像 `User` 对象的 `password` 字段和类似敏感数据。
要告诉导出器不导出这些项，请使用 `@RestResource` 并设置 `exported = false` 注解它们。

例如，要跳过导出存储库，您可以创建类似于下例的存储库定义：

====
[source,java]
----
@RepositoryRestResource(exported = false)
interface PersonRepository extends CrudRepository<Person, Long> {}
----
====

要跳过导出查询方法，可以使用 `@RestResource(exported = false)` 如下注解查询方法：

====
[source,java]
----
@RepositoryRestResource(path = "people", rel = "people")
interface PersonRepository extends CrudRepository<Person, Long> {

  @RestResource(exported = false)
  List<Person> findByName(String name);
}
----
====

同样，要跳过导出字段，可以使用 `@RestResource(exported = false)` 如下注解该字段：

====
[source,java]
----
@Entity
public class Person {

  @Id @GeneratedValue private Long id;

  @OneToMany
  @RestResource(exported = false)
  private Map<String, Profile> profiles;
}
----
====

WARNING: 投影提供了更改导出内容并有效<<projections-excerpts.hidden-data,忽略这些设置>>的方法。如果您针对同一域对象创建任何投影，确保不导出字段。

[[customizing-sdr.hiding-repository-crud-methods]]
== 隐藏存储库CRUD方法

如果您不想公开 `CrudRepository`上的save或delete方法，可以通过重写您想要关闭的方法并在该重写版本上使用 `@RestResource(exported = false)` 设置。
例如，要阻止HTTP用户调用 `CrudRepository` 的delete方法，请重写所有这些方法并将注解添加到重写的方法上，如下：

====
[source,java]
----
@RepositoryRestResource(path = "people", rel = "people")
interface PersonRepository extends CrudRepository<Person, Long> {

  @Override
  @RestResource(exported = false)
  void delete(Long id);

  @Override
  @RestResource(exported = false)
  void delete(Person entity);
}
----
====

WARNING: 重要的是您要重写 _两个_ `delete` 方法。为了提高运行时性能，导出器目前使用一种有点天真的算法来确定使用哪种CRUD方法。
您当前无法关闭接收ID的 `delete` 版本，但导出接收实体实例的版本。目前，您可以导出或不导出 `delete` 方法。如果想关闭它们，请记住必须使用 `exported = false` 注解这两个版本。
