[[customizing-sdr.customizing-json-output]]
= 自定义JSON输出

有时在您的应用程序中，您需要提供指向特定实体其他资源的链接。例如，可以通过指向当前购物车的链接或管理与该实体相关资源的链接来丰富 `Customer` 响应。
Spring Data REST提供了与 https://github.com/SpringSource/spring-hateoas[Spring HATEOAS]的集成，并提供了一个让您更改输出到客户端的资源表示的扩展钩子。

== `ResourceProcessor` 接口

Spring HATEOAS为处理实体定义了 `ResourceProcessor<>` 接口。所有 `ResourceProcessor&lt;Resource&lt;T&gt;&gt;` 类型的bean都由Spring Data REST导出器自动获取，并在序列化 `T` 类型的实体时触发。

例如，要为 `Person` 实体定义处理器，请将类似于以下的 `@Bean`（取自Spring Data REST测试）添加到 `ApplicationContext`：

====
[source,java]
----
@Bean
public ResourceProcessor<Resource<Person>> personProcessor() {

   return new ResourceProcessor<Resource<Person>>() {

     @Override
     public Resource<Person> process(Resource<Person> resource) {

      resource.add(new Link("http://localhost:8080/people", "added-link"));
      return resource;
     }
   };
}
----
====

IMPORTANT: 前面示例硬编码指向 `http://localhost:8080/people` 的链接。如果您希望链接到应用程序中的Spring MVC端点，请考虑使用Spring HATEOAS的 https://github.com/spring-projects/spring-hateoas#building-links-pointing-to-methods[`linkTo(...)`]方法，以避免管理URL。

== 添加链接

您可以通过调用 `resource.add(Link)` 来添加指向实体默认表示的链接，如前面示例所示。 您添加到 `Resource` 的任何链接都会添加到最终输出中。

== 自定义表示

Spring Data REST导出器在创建输出表示之前执行任何发现的 `ResourceProcessor` 实例。它通过使用内部 `ConversionService` 注册 `Converter<Entity, Resource>` 实例来实现此目的。
这是负责创建指向引用实体（例如，对象的JSON表示中 `_links` 属性下的那些对象）的链接的组件。
它接收 `@Entity` 并迭代其属性，为 `Repository` 管理的属性创建链接，并复制任何嵌入或简单属性。

但是，如果您的项目需要以不同的格式输出，则可以用您自己的完全替换默认的传出JSON表示。
如果您在 `ApplicationContext` 中注册自己的 `ConversionService` 并注册自己的 `Converter<Entity, Resource>`，那么您可以返回一个您选择的 `Resource` 实现。