[[representations]]
= 域对象表示（对象映射）

Spring Data REST返回一个对应于HTTP请求中指定的 `Accept` 类型的域对象的表示。

目前，仅支持JSON表示。其他表示类型将来可以通过添加适当的转换器并使用适当的内容类型更新控制器方法来支持。

有时，Spring Data REST的 `ObjectMapper` 的行为（该行为已经专门配置为使用可以将域对象转换为链接并再次返回的智能序列化器）可能无法正确处理您的域模型。
可以通过很多方式构建数据，您可能会发现自己的域模型没有正确地转换为JSON。在这些情况下，尝试并以通用方式支持复杂域模型有时也不实用。
有时，根据复杂性，甚至不可能提供通用解决方案。

== 将自定义序列化器和反序列化器添加到Jackson的ObjectMapper中

为了适应最大比例的用例，Spring Data REST非常努力地正确呈现对象图。它尝试将非托管bean序列化为普通的POJO，并在必要时尝试创建托管bean的链接。
但是，如果您的域模型不易于阅读或编写普通JSON，您可能想使用自己的自定义映射、序列化器和反序列化器来配置Jackson的ObjectMapper。

==== 抽象类注册

您可能需要挂钩的一个关键配置点是在域模型中使用抽象类（或接口）时。Jackson默认不会知道为接口创建什么实现。考虑以下示例：

====
[source,java]
----
@Entity
public class MyEntity {
  @OneToMany
  private List<MyInterface> interfaces;
}
----
====

在默认配置中，Jackson在将新数据POST到导出器时不知道要实例化哪个类。您需要通过注解告诉Jackson，或者（更清楚地）通过使用 `Module` 注册类型映射。

要将自己的Jackson配置添加到Spring Data REST使用的 `ObjectMapper`，请覆盖 `configureJacksonObjectMapper` 方法。
一个具有特殊模块来处理序列化和反序列化 `PersistentEntity` 对象的 `ObjectMapper` 实例传递给该方法。您也可以注册自己的模块，如下例所示：

====
[source,java]
----
@Override
protected void configureJacksonObjectMapper(ObjectMapper objectMapper) {
    objectMapper.registerModule(new SimpleModule("MyCustomModule") {
        @Override
        public void setupModule(SetupContext context) {
            context.addAbstractTypeResolver(
                new SimpleAbstractTypeResolver().addMapping(MyInterface.class,
                                                            MyInterfaceImpl.class)
            );
        }
    });
}
----
====

一旦您可以访问 `Module` 中的 `SetupContext` 对象，就可以使用各种很酷的东西来配置Jackson的JSON映射。
您可以在Jackson的wiki上阅读有关 http://wiki.fasterxml.com/JacksonFeatureModules[`Module` 实例如何工作]的更多信息。

=== 为域类型添加自定义序列化器

如果您想以特殊方式序列化或反序列化域类型，可以使用Jackson的 `ObjectMapper` 注册自己的实现，Spring Data REST导出器透明地正确处理这些域对象。
要从 `setupModule` 方法实现添加序列化器，您可以做类似以下的事情：

====
[source,java]
----
@Override
public void setupModule(SetupContext context) {
  SimpleSerializers serializers = new SimpleSerializers();
  SimpleDeserializers deserializers = new SimpleDeserializers();

  serializers.addSerializer(MyEntity.class, new MyEntitySerializer());
  deserializers.addDeserializer(MyEntity.class, new MyEntityDeserializer());

  context.addSerializers(serializers);
  context.addDeserializers(deserializers);
}
----
====

